In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Mozassam Imam\Desktop\AI\CampusX\ML\19_Understanding_data\train_titanic.csv",usecols = ['Age','Fare','SibSp','Parch','Survived'])

In [3]:
df.head()

   Survived   Age  SibSp  Parch     Fare
0         0  22.0      1      0   7.2500
1         1  38.0      1      0  71.2833
2         1  26.0      0      0   7.9250
3         1  35.0      1      0  53.1000
4         0  35.0      0      0   8.0500

In [4]:
df.dropna(inplace=True)

In [5]:
df.isnull().sum()

Survived    0
Age         0
SibSp       0
Parch       0
Fare        0
dtype: int64

In [6]:
df['family']=df['SibSp']+df['Parch']

In [7]:
df.head()

   Survived   Age  SibSp  Parch     Fare  family
0         0  22.0      1      0   7.2500       1
1         1  38.0      1      0  71.2833       1
2         1  26.0      0      0   7.9250       0
3         1  35.0      1      0  53.1000       1
4         0  35.0      0      0   8.0500       0

In [11]:
df.drop(columns = ['SibSp','Parch'],inplace=True)

In [12]:
df.head()

   Survived   Age     Fare  family
0         0  22.0   7.2500       1
1         1  38.0  71.2833       1
2         1  26.0   7.9250       0
3         1  35.0  53.1000       1
4         0  35.0   8.0500       0

In [13]:
X=df.iloc[:,1:]
y=df['Survived']

In [14]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [15]:
X.head()

    Age     Fare  family
0  22.0   7.2500       1
1  38.0  71.2833       1
2  26.0   7.9250       0
3  35.0  53.1000       1
4  35.0   8.0500       0

In [18]:
from sklearn.model_selection import train_test_split, cross_val_score

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [20]:
X_train.head()

      Age     Fare  family
328  31.0  20.5250       2
73   26.0  14.4542       1
253  30.0  16.1000       1
719  33.0   7.7750       0
666  25.0  13.0000       0

In [21]:
from sklearn.tree import DecisionTreeClassifier

In [22]:
from sklearn.metrics import accuracy_score

In [23]:
# without binarization
clf=DecisionTreeClassifier()
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
accuracy_score(y_test,y_pred)

0.6293706293706294

In [24]:
np.mean(cross_val_score(clf,X,y,scoring='accuracy'))

0.658248793460061

# Applying binarization

In [27]:
from sklearn.preprocessing import Binarizer
from sklearn.compose import ColumnTransformer

In [30]:
trf = ColumnTransformer([
    ('bin',Binarizer(copy=False),['family'])
],remainder='passthrough')

In [31]:
X_train_trf = trf.fit_transform(X_train)
X_test_trf = trf.transform(X_test)

In [34]:
pd.DataFrame(X_train_trf,columns=['family','Age','Fare'])

     family   Age      Fare
0       1.0  31.0   20.5250
1       1.0  26.0   14.4542
2       1.0  30.0   16.1000
3       0.0  33.0    7.7750
4       0.0  25.0   13.0000
..      ...   ...       ...
566     1.0  46.0   61.1750
567     0.0  25.0   13.0000
568     0.0  41.0  134.5000
569     1.0  33.0   20.5250
570     0.0  33.0    7.8958

[571 rows x 3 columns]

In [35]:
clf = DecisionTreeClassifier()
clf.fit(X_train_trf,y_train)
y_pred2=clf.predict(X_test_trf)
accuracy_score(y_test,y_pred2)

0.6083916083916084

In [38]:
X_trf=trf.fit_transform(X)
np.mean(cross_val_score(clf,X_trf,y,scoring='accuracy'))

0.6190682556879741