In [34]:
import pandas as pd
import numpy as np

In [35]:
date = pd.read_csv('orders.csv')
time= pd.read_csv('messages.csv')

In [36]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [37]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [38]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [39]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# Working with date

In [40]:
# converting the object date in datetime datatype
date['date']=pd.to_datetime(date['date'])

In [41]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

<h2>Extracting year</h2>

In [42]:
date['date_year']=date['date'].dt.year

In [43]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

<h2>Extracting Month</h2>

In [44]:
date['date_month']=date['date'].dt.month
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [45]:
date['date_month_name']=date['date'].dt.month_name()

In [46]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

<h2>Extracting day</h2>

In [49]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [51]:
date['date_day_ofweek']=date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_ofweek
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [54]:
date['date_day_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_ofweek,date_day_neme,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,Sunday

In [59]:
# is weekend or not?
date['is_weekend']=np.where(date['date_day_name'].isin(['Saturday','Sunday']),1,0)  # we can write true,false in place of 1,0
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_ofweek,date_day_neme,date_day_name,is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,Sunday,1

In [61]:
# weak of the year
date['week_no'] = date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_ofweek,date_day_neme,date_day_name,is_weekend,week_no
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,Sunday,1,1

Time between two dates

In [62]:
import datetime as dt

In [65]:
tdate = dt.datetime.today()
tdate

datetime.datetime(2026, 9, 4, 15, 27, 13, 316542)

In [66]:
tdate-date['date']

0     2460 days 15:27:13.316542
1     2942 days 15:27:13.316542
2     2873 days 15:27:13.316542
3     2575 days 15:27:13.316542
4     2798 days 15:27:13.316542
                 ...
995   2888 days 15:27:13.316542
996   2829 days 15:27:13.316542
997   2677 days 15:27:13.316542
998   2742 days 15:27:13.316542
999   2516 days 15:27:13.316542
Name: date, Length: 1000, dtype: timedelta64[ns]

In [70]:
# if you want just days then
(tdate-date['date']).dt.days

0      2460
1      2942
2      2873
3      2575
4      2798
       ...
995    2888
996    2829
997    2677
998    2742
999    2516
Name: date, Length: 1000, dtype: int64

In [77]:
# Months passed

months_passed = (
    (tdate.year - date['date'].dt.year) * 12
    + (tdate.month - date['date'].dt.month)
)

print(months_passed)

0      81
1      97
2      95
3      85
4      92
       ..
995    95
996    93
997    88
998    90
999    83
Name: date, Length: 1000, dtype: int32

# Time

In [78]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [81]:
time['date'] = pd.to_datetime(time['date'])

In [82]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [83]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [84]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00