In [26]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer, KNNImputer

In [27]:
df=pd.read_csv(r"C:\Users\Mozassam Imam\Desktop\AI\CampusX\ML\19_Understanding_data\train_titanic.csv",usecols=['Age','Pclass','Fare','Survived'])

In [28]:
df.head()

   Survived  Pclass   Age     Fare
0         0       3  22.0   7.2500
1         1       1  38.0  71.2833
2         1       3  26.0   7.9250
3         1       1  35.0  53.1000
4         0       3  35.0   8.0500

In [29]:
df.isnull().sum()

Survived      0
Pclass        0
Age         177
Fare          0
dtype: int64

In [30]:
X=df.drop(columns=['Survived'])
y=df['Survived']

In [31]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.2, random_state=2)

In [32]:
X_train

     Pclass   Age      Fare
30        1  40.0   27.7208
10        3   4.0   16.7000
873       3  47.0    9.0000
182       3   9.0   31.3875
876       3  20.0    9.8458
..      ...   ...       ...
534       3  30.0    8.6625
584       3   NaN    8.7125
493       1  71.0   49.5042
527       1   NaN  221.7792
168       1   NaN   25.9250

[712 rows x 3 columns]

In [46]:
knn = KNNImputer(n_neighbors=3,weights='distance')

In [47]:
X_train_trf=knn.fit_transform(X_train)
X_test_trf=knn.transform(X_test)

In [48]:
lr = LogisticRegression()

In [49]:
lr.fit(X_train_trf,y_train)
y_pred=lr.predict(X_test_trf)

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(y_test,y_pred)

0.7150837988826816

In [52]:
si = SimpleImputer()

In [53]:
X_train_trf1=si.fit_transform(X_train)
X_test_trf1=si.transform(X_test)

lr.fit(X_train_trf1,y_train)

y_pred1 = lr.predict(X_test_trf1)
accuracy_score(y_test,y_pred1)

0.6927374301675978

In [56]:
def knn_at_every_value(X_train,X_test,y_train,y_test):
    for i in range (1,20):
        knn = KNNImputer(n_neighbors=i,weights='distance')
        X_train_trf=knn.fit_transform(X_train)
        X_test_trf=knn.transform(X_test)
        lr.fit(X_train_trf,y_train)
        y_pred=lr.predict(X_test_trf)
        print(f"accuracy when neighbors is {i} ",accuracy_score(y_test,y_pred))

In [57]:
knn_at_every_value(X_train,X_test,y_train,y_test)

accuracy when neighbors is 1  0.6871508379888268
accuracy when neighbors is 2  0.7150837988826816
accuracy when neighbors is 3  0.7150837988826816
accuracy when neighbors is 4  0.7094972067039106
accuracy when neighbors is 5  0.7094972067039106
accuracy when neighbors is 6  0.7039106145251397
accuracy when neighbors is 7  0.7039106145251397
accuracy when neighbors is 8  0.7039106145251397
accuracy when neighbors is 9  0.7039106145251397
accuracy when neighbors is 10  0.7039106145251397
accuracy when neighbors is 11  0.7039106145251397
accuracy when neighbors is 12  0.7039106145251397
accuracy when neighbors is 13  0.7039106145251397
accuracy when neighbors is 14  0.7039106145251397
accuracy when neighbors is 15  0.7039106145251397
accuracy when neighbors is 16  0.7039106145251397
accuracy when neighbors is 17  0.7039106145251397
accuracy when neighbors is 18  0.7039106145251397
accuracy when neighbors is 19  0.7039106145251397

In [62]:
def knn_at_every_value1(X_train,X_test,y_train,y_test):
    neighbors=[]
    accuracies=[]
    for i in range (1,21):
        knn = KNNImputer(n_neighbors=i,weights='distance')
        
        X_train_trf=knn.fit_transform(X_train)
        X_test_trf=knn.transform(X_test)
        
        lr.fit(X_train_trf,y_train)
        y_pred=lr.predict(X_test_trf)
        
        accuracy = accuracy_score(y_test, y_pred)
        
        neighbors.append(i)
        accuracies.append(accuracy)
    result=pd.DataFrame({
    "n_neighbors":neighbors,
    "accuracy":accuracies
    })
    return result

In [68]:
knn_at_every_value1(X_train,X_test,y_train,y_test)

    n_neighbors  accuracy
0             1  0.687151
1             2  0.715084
2             3  0.715084
3             4  0.709497
4             5  0.709497
5             6  0.703911
6             7  0.703911
7             8  0.703911
8             9  0.703911
9            10  0.703911
10           11  0.703911
11           12  0.703911
12           13  0.703911
13           14  0.703911
14           15  0.703911
15           16  0.703911
16           17  0.703911
17           18  0.703911
18           19  0.703911
19           20  0.703911

In [69]:
import pandas as pd
import numpy as np
data = {
 "Student_ID": [101, 102, 103, 104, 102, 105, 106, 106],
 "Name": ["Rahul", "Anjali", "Amit", "Priya", "Anjali", "Neha", "Rohit", "Rohit"],
 "Age": [20, 21, np.nan, 22, 21, np.nan, 23, 23],
 "Gender": ["M", "F", "M", "F", "F", "F", "M", "M"],
 "Marks": [85, 90, 78, np.nan, 90, 88, 92, 92]
    }
df = pd.DataFrame(data)
print(df)

   Student_ID    Name   Age Gender  Marks
0         101   Rahul  20.0      M   85.0
1         102  Anjali  21.0      F   90.0
2         103    Amit   NaN      M   78.0
3         104   Priya  22.0      F    NaN
4         102  Anjali  21.0      F   90.0
5         105    Neha   NaN      F   88.0
6         106   Rohit  23.0      M   92.0
7         106   Rohit  23.0      M   92.0

In [72]:
df

   Student_ID    Name   Age Gender  Marks
0         101   Rahul  20.0      M   85.0
1         102  Anjali  21.0      F   90.0
2         103    Amit   NaN      M   78.0
3         104   Priya  22.0      F    NaN
4         102  Anjali  21.0      F   90.0
5         105    Neha   NaN      F   88.0
6         106   Rohit  23.0      M   92.0
7         106   Rohit  23.0      M   92.0

In [73]:
df.isnull().sum()

Student_ID    0
Name          0
Age           2
Gender        0
Marks         1
dtype: int64

In [76]:
df.duplicated().sum()

2

In [77]:
si = SimpleImputer()

In [ ]:
X_train